config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :brands do
    resources :perfumes
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :perfumes, dependent: :destroy
end

app/models/perfume.rb
class Perfume < ApplicationRecord
  belongs_to :brand
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def index
    @brands = Brands.all
  end

  def new
    @brand = Brand.new
  end

  def show
    @brand = Brand.find_by_id(params[:id])
    @perfume = Perfume.find_by_id(params[:id])
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      redirect_to @brand
    else
      render 'new'
    end
  end

  private

  def brand_params
    params.require(:brand).permit(:name)
  end

end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController
  def index
    @perfumes = Perfume.all
  end

  def new
    @perfume = Perfume.new
  end

  def show
    @perfume = Perfume.find_by_id(params[:id])
    get_brand
  end

  def create
    get_brand
    @perfume = @brand.perfumes.new(perfume_params)
    @perfume.rating = 0
    @perfume.brand_id = @brand.id
     if @perfume.save
      redirect_to @brand
    else
      render 'new'
    end
  end

  private

  def get_brand
    @brand = Brand.find(params[:brand_id])
  end
  
  def perfume_params
    params.require(:perfume).permit(:name, :size, :rating, :description, :season, :brand_id)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @perfumes = Perfume.all
    @brands = Brand.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/perfumes_helper.rb
module PerfumesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/brands/new.html.erb
<h1>Add a Perfume to Your Collection</h1>
  <%= form_with model: @brand, local: true do |f|  %>
    <% if @brand.errors.any? %>
      <div id="explain_error">
        <h2> Uh oh! <%= pluralize(@brand.errors.count, "error") %> prohibited this from being saved: </h2>
        <ul>
          <% @brand.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

    <%= f.label "Brand Name:" %>
    <%= f.text_field :name %>
    <br>

  <%= f.submit%>
  <% end %>

app/views/brands/show.html.erb
<h1><%= @brand.name %></h1>

<% @brand.perfumes.each do |perfume| %>
  <li><%= link_to perfume.name, brand_perfume_path(@brand, perfume) %> </li>
<% end %>

<%= render 'perfumes/new' %>
<br><br>
<%= link_to 'Home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Perfumery</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/perfumes/_new.html.erb
<h1>Add a Perfume to Your <%= @brand.name %> Collection: </h1>
  <%= form_with(model: [@brand, @brand.perfumes.build]) do |f|  %>


    <%= f.label "Perfume Name:" %>
    <%= f.text_field :name %>
    <br>
    <%= f.label "Description:" %>
    <%= f.text_area :description %>
    <br>
    <%= f.label "Size:" %>
    <%= f.select :size, %w[sample dram full-size other] %>
    <br>
    <%= f.label "Season:" %>
    <%= f.select :season, %w[spring summer fall winter] %>
    <br>

  <%= f.submit%>
  <% end %>

app/views/perfumes/show.html.erb
Perfume: <%= @perfume.name %>
<br><br>
Size: <%= @perfume.size %>
<br><br>
Description: <%= @perfume.description %>
<br><br>
Season: <%= @perfume.season %>
<br><br>
Brand: <%= @brand.name %>
<br><br>


<%= link_to 'Home', root_path %><br>
<%= link_to 'Back to Brand', brand_path(@perfume.brand_id) %>

app/views/welcome/index.html.erb
<h1> Welcome to your Perfume Collection </h1>

<h2> Your current perfumes:</h2>
<% @perfumes.each do |perfume| %>
  <li><%= link_to perfume.name, brand_perfume_path(perfume.brand_id, perfume.id) %></li>



<% end %>

<h2> Brands you own: </h2>
<% @brands.each do |brand| %>
  <li> <%= link_to brand.name, brand_path(brand)  %>
<% end %>
<br><br>
<%= link_to "Add a brand", new_brand_path %>